github.com:
    users:
        wildsrincon:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: wildsrincon
